github.com:
    users:
        wildsrincon:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: wildsrincon
